functionsDirectory = "D:\\Projects\\Clients\\lux\\netlify\\functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "D:\\Projects\\Clients\\lux\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"
functions = "D:\\Projects\\Clients\\lux\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]